version: '3.6'
x-defaults: &defaults
  env_file: .env
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  metadata:
    <<: *defaults
    container_name: metadata
    image: "registry.gitlab.com/trivialsec/workers/metadata:${IMAGE_TAG:-latest}"
    # entrypoint: "bash -c 'tail -f /dev/null'"
    environment:
      - CONFIG_FILE=${CONFIG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${TF_VAR_aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${TF_VAR_aws_secret_access_key}
    volumes:
      - ./src/metadata:/srv/app/metadata
      - ./src/worker:/srv/app/worker
      - ./src/main.py:/srv/app/main.py
      - ./src/s3_upload.py:/srv/app/s3_upload.py
      - ./docker/conf/config-${BUILD_ENV}.yaml:/srv/app/config.yaml
  testssl:
    <<: *defaults
    image: trivialsec/worker/testssl
    # entrypoint: "bash -c 'tail -f /dev/null'"
    environment:
      - CONFIG_FILE=${CONFIG_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
      - AWS_ACCESS_KEY_ID=${TF_VAR_aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${TF_VAR_aws_secret_access_key}
    volumes:
      - ./docker/drill/bin:/srv/app/lib/bin
      - ./src/testssl:/srv/app/testssl
      - ./src/worker:/srv/app/worker
      - ./src/main.py:/srv/app/main.py
      - ./src/s3_upload.py:/srv/app/s3_upload.py
      - ./docker/conf/config-${BUILD_ENV}.yaml:/srv/app/config.yaml
    networks:
      default:
        aliases:
          - metadata

networks:
  default:
    external:
      name: trivialsec
