version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - [%(levelname)s] %(message)s'
handlers:
  logfile:
    class: logging.FileHandler
    filename: /tmp/application.log
    level: INFO
    formatter: simple
loggers:
  circus:
    level: INFO
    handlers: [logfile]
    propagate: no
  amass:
    level: WARNING
    handlers: [logfile]
    propagate: no
  drill:
    level: WARNING
    handlers: [logfile]
    propagate: no
root:
  level: INFO
  handlers: [logfile]
