---
app:
  env: Dev
  version: 21.1.27
  log_file: /tmp/application.log
  log_level: DEBUG
  frontend:
    site_scheme: "http://"
    site_domain: localhost:5000
    socket_scheme: "http://"
    socket_domain: localhost:5080
  backend:
    socket_scheme: "http://"
    socket_domain: sockets:5080
  cve:
    url: http://search:5180
  nameservers:
    - 1.1.1.1     # Cloudflare
    - 8.8.8.8     # Google
    - 64.6.64.6   # Verisign
    - 74.82.42.42 # Hurricane Electric
    - 77.88.8.1   # Yandex.DNS
    - 9.9.9.9     # Quad9
  nmap:
    ports: 20-23,25,53,57,67-69,80,81,82,107-113,115,118-119,135,137-139,143,153,156,170,177,179,194,209,213,218,220,300,311,366,369-371,383,384,387,389,399,427,433,434,443-445,464,465,475,491,514,515,517,518,520,521,524,530-533,540,546-548,556,560,561,563-585,587,591,593,601,604,623,625,631,635,636,639,641,646-648,653-655,657,660,666,674,688,690,691,706,711,712,749-754,760,782,783,808,832,843,847,848,873,953-61000

redis:
  host: redis
  ssl: False
  ttl: 300

mysql:
  database: trivialsec
  user: root
  host: mysql

aws:
  region_name: ap-southeast-2
  archive_bucket: trivialsec-assets
  archive_object_prefix: archive/
  public_bucket: trivialsec-assets
  public_object_prefix: static/

sendgrid:
  templates:
    invitations: d-ddd501dd76634f12bdba7dfcee416270
    registrations: d-1259c22153484803bdc4d6cb490571a6
    subscriptions: d-14c95c71ba5f40deac27eb8e0bcd0373
    updated_email: d-30f820fc0f8a4f4d9f0fd5592a7419b5
    reset_password: d-d6ec3c4db69b46cd8a4bf873ef03bf16
  groups:
    notifications: 14193
    focus_group: 14107
    subscriptions: 14106
    marketing: 14105
  lists:
    subscribers: a656c506-1a36-45ad-ad29-bb54db25ccd9

stripe:
  account: acct_1HTJBRGZtHTgMn6l
  products:
    enterprise:
      product_id: prod_I3YKq0kh5u21Gy
    standard:
      product_id: prod_I3QXcZm1iVM4nZ
      monthly: price_1HTJfyGZtHTgMn6lhohsngNb
      yearly: price_1HTJfzGZtHTgMn6lUTHe2gbq
    professional: 
      product_id: prod_I3Qc8SWBstGEJg
      monthly: price_1HTJkpGZtHTgMn6lgDC7UDf0
      yearly: price_1HTJkpGZtHTgMn6l1xGWhRVb

amass:
  output_directory: /tmp
  maximum_dns_queries: 20000
  public_dns_resolvers: true
  score_resolvers: true
  monitor_resolver_rate: true
  bruteforce:
    enabled: true
    wordlist_file: /srv/app/lib/wordlists/all.txt
  alterations:
    enabled: false
    add_numbers: true
  sources_minimum_ttl: 1440
  sources:
    alienvault:
      name: AlienVault
      disabled: false
      ttl: 10080
    binaryedge:
      name: BinaryEdge
      disabled: false
      ttl: 10080
    bufferover:
      name: BufferOver
      disabled: false
      ttl: 10080
    builtwith:
      name: BuiltWith
      disabled: false
      ttl: 10080
    c99:
      name: C99
      disabled: false
      ttl: 4320
    censys:
      name: Censys
      disabled: false
      ttl: 10080
    chaos:
      name: Chaos
      disabled: false
      ttl: 4320
    cloudflare:
      name: Cloudflare
      disabled: false
    circl:
      name: CIRCL
      disabled: false
      ttl: 10080
    dnsdb:
      name: DNSDB
      disabled: false
      ttl: 10080
    dnstable:
      name: DNSTable
      disabled: false
      ttl: 4320
    facebookct:
      name: FacebookCT
      disabled: false
      ttl: 4320
    github:
      name: GitHub
      disabled: false
      ttl: 4320
    hackerone:
      name: HackerOne
      disabled: false
      ttl: 4320
    hackertarget:
      name: HackerTarget
      disabled: false
      ttl: 4320
    networksdb:
      name: NetworksDB
      disabled: false
      ttl: 10080
    recondev:
      name: ReconDev
      disabled: false
    passivetotal:
      name: PassiveTotal
      disabled: false
      ttl: 10080
    rapiddns:
      name: RapidDNS
      disabled: false
      ttl: 4320
    riddler:
      name: Riddler
      disabled: false
      ttl: 4320
    securitytrails:
      name: SecurityTrails
      disabled: false
      ttl: 1440
    shodan:
      name: Shodan
      disabled: false
      ttl: 10080
    sitedossier:
      name: SiteDossier
      disabled: false
      ttl: 4320
    spyse:
      name: Spyse
      disabled: false
      ttl: 4320
    twitter:
      name: Twitter
      disabled: false
      ttl: 10080
    umbrella:
      name: Umbrella
      disabled: false
      ttl: 10080
    urlscan:
      name: URLScan
      disabled: false
      ttl: 10080
    virustotal:
      name: VirusTotal
      disabled: false
      ttl: 10080
    whoisxml:
      name: WhoisXML
      disabled: false
      ttl: 10080
    zetalytics:
      name: ZETAlytics
      disabled: false
      ttl: 1440
    zoomeye:
      name: ZoomEye
      disabled: false
      ttl: 1440
